### PR TITLE
[#245] Get first unread chapter from original chapter list

### LINKED ISSUE #245: [Bug] Resume button opens latest chapter when chapter sorted in reverse
## Device information
- Tachidesk version: v0.7.0-r1201
- Server Operating System: Ubuntu 22.04.1 LTS
- Server Desktop Environment: XFCE4
- Server JVM version: openjdk 18.0.2-ea 2022-07-19
- Client Operating System: Ubuntu 22.04.1 LTS
- Client Web Browser: Chromium 110.0.5481.77 

## Steps to reproduce
1. Go to any manga's page
2. Click the sort button and choose reverse by source
3. and go back to manga page click to resume button

### Expected behavior
Open the latest chapter that I left
### Actual behavior
It open the manga's latest published chapter
## Other details
Other issue was closed by bot so decided to open it myself.

### PR DESCRIPTION
**Pull request by schroda**
fixes #245 

The first unread chapter was retrieved from the filtered and sorted chapter list, which could result in e.g. incorrectly recognizing the latest released chapter as the first unread chapter.

Ideally the server would return the manga with its last read chapter, but this is currently not available.

### CODE REVIEW

File: src/components/manga/ChapterList.tsx [hunk 1]
```diff
@@ -110,11 +110,11 @@ const ChapterList: React.FC<IProps> = ({ mangaId }) => {
 
     const firstUnreadChapter = useMemo(
         () =>
-            visibleChapters
+            chapters
                 .slice()
                 .reverse()
-                .find((c) => c.read === false),
-        [visibleChapters],
+                .find((chapter) => chapter.read === false),
```
Comment (akabhirav) [inline src/components/manga/ChapterList.tsx:116]:
```suggestion
                .find((chapter) => !chapter.read),
```
just a nitpick, since read value can only be true and false

**Review by akabhirav — APPROVED** [review]
LGTM
